---
title: "Analysis"
author: "Jair Alva Mendoza"
date: "28/4/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

###Libraries
```{r}
library(tidyverse)
library(plm)
library(stargazer)
library(performance)
library(xtable)
# corplot
library(psych)
library(polycor)
library(ggcorrplot)
library(PerformanceAnalytics)
library(corrplot)
```

```{r}
load("data.RDta")
```
## Descreptive
```{r}
# Relation of labor mentions between right and left
data |> 
  arrange(year) |> 
  select(year, lab_left, lab_right) |> 
  group_by(year) |> 
  summarise_all(mean) |> 
  ggplot() +
  geom_line(aes(x = year, y = lab_left), color ="blue", show.legend = T) + 
  geom_line(aes(x = year, y = lab_right)) +
  theme_classic()
```

  + Correlation matrix
```{r}
matrixcor <- cor(data[,c(8, 22, 26, 15, 19, 18, 16, 14)], 
                 use = "pairwise.complete.obs")
cor.plot(matrixcor)
```
  
  + Descriptive table
```{r}
min = data |> 
  select(vot_ed, prev_left_cab_num, per_foreign_pop, var_gdp, pol_viol,
         age_stand_death, avr_educ, pub_serv_rural, pol_pol)  |> 
  summarise_all(min, na.rm = T) |> 
  pivot_longer(vot_ed:pol_pol, names_to = "variables", values_to = "Min")

max = data |> 
  select(vot_ed, prev_left_cab_num, per_foreign_pop, var_gdp, pol_viol,
         age_stand_death, avr_educ, pub_serv_rural, pol_pol) |> 
  summarise_all(max, na.rm = T) |> 
  pivot_longer(vot_ed:pol_pol, names_to = "variables", values_to = "Max") 
  

mean = data |> 
  select(vot_ed, prev_left_cab_num, per_foreign_pop, var_gdp, pol_viol,
         age_stand_death, avr_educ, pub_serv_rural, pol_pol) |> 
  summarise_all(mean, na.rm = T) |> 
  pivot_longer(vot_ed:pol_pol, names_to = "variables", values_to = "Mean")
 
median = data |> 
  select(vot_ed, prev_left_cab_num, per_foreign_pop, var_gdp, pol_viol,
         age_stand_death, avr_educ, pub_serv_rural, pol_pol) |> 
  summarise_all(median, na.rm = T) |> 
  pivot_longer(vot_ed:pol_pol, names_to = "variables", values_to = "Median")

sd = data |> 
  select(vot_ed, prev_left_cab_num, per_foreign_pop, var_gdp, pol_viol,
         age_stand_death, avr_educ, pub_serv_rural, pol_pol) |> 
  summarise_all(sd, na.rm = T) |> 
  pivot_longer(vot_ed:pol_pol, names_to = "variables", values_to = "SD")

descriptives = min |> 
  left_join(max) |> 
  left_join(mean) |> 
  left_join(median) |> 
  left_join(sd)

print(xtable(descriptives, type = "latex"), file = "table0.tex")
```
  
## Linear regression
```{r}
mod1 = lm(vot_ed  ~ lab_left*prev_left_cab, data = data)
summary(mod1)
```

## Panel data
```{r}
#Estimating LSDV

LSDV <-lm(vot_ed  ~ lab_left*prev_left_cab + factor(country_name), data= data)
summary(LSDV)

# Fixed effects
fixed <- plm(vot_ed  ~ lab_left*prev_left_cab, data= data, 
             index=c("country_name", "year"), model="within")
summary(fixed)

fixef(fixed)

pFtest(fixed, mod1) # Testing for fixed effects, null: POOLED better than fixed

write.table(test1, file = "test1.html")

# Random effects
random <- plm(vot_ed  ~ lab_left*prev_left_cab, data= data, 
             index=c("country_name", "year"), model="random")
summary(random)

#choosing between fixed or random the Hausman test
phtest(fixed, random) # null: RANDOM better than fixed 
```

### Summary
```{r}
stargazer(mod1, fixed, random,  
          title="Table 1. Linear Regressions", type="text", 
          column.labels=c("Pooled OLS", "Fixed Effects", "Random Effects"),
          covariate.labels = c("laboral mentions", "Prev Cab Left",
                               "laboral mentions:Prev Cab Left",
                               "Constant"),
          dep.var.labels = c("Vote share PRR parties"),
          df=FALSE, digits=4, out = "table1.tex")
```

### With control variables
```{r}
random2 <- plm(vot_ed  ~ lab_left*prev_left_cab + 
                 per_foreign_pop + var_gdp, data= data, 
             index=c("country_name", "year"), model="random")

random3 <- plm(vot_ed  ~ lab_left*prev_left_cab + pol_viol + age_stand_death, 
               data= data, 
             index=c("country_name", "year"), model="random")

random4 <- plm(vot_ed  ~ lab_left*prev_left_cab + avr_educ + pub_serv_rural, 
               data= data, 
             index=c("country_name", "year"), model="random")

random5 <- plm(vot_ed  ~ lab_left*prev_left_cab + pol_pol, 
               data= data, 
             index=c("country_name", "year"), model="random")

random6 <- plm(vot_ed  ~ lab_left*prev_left_cab + per_foreign_pop + var_gdp +
                 pol_viol + age_stand_death + avr_educ + pub_serv_rural + pol_pol, 
               data= data, 
             index=c("country_name", "year"), model="random")

stargazer(random, random2, random3, random4, random5, random6,
          title="Table 2. Random Effect Regressions", type="text", 
          covariate.labels = c("laboral mentions", "Prev Cab Left",
                               "% Foreigners", "Var GDP", "Political Violence",
                               "Rate of violent deaths", "Average of Education",
                               "Urban Population", "Political Polarization",
                               "laboral mentions:Prev Cab Left",
                               "Constant"),
          dep.var.labels = c("Vote share PRR parties"),
          df=FALSE, digits=4, out = "table2_2.html")

r2(random4)

check_collinearity(random4)
```

